# Generated by Django 3.2.9 on 2021-11-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masspoint',
            name='mass',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='masspoint',
            name='x_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='masspoint',
            name='y_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='masspoint',
            name='z_value',
            field=models.FloatField(default=0),
        ),
    ]
