# Generated by Django 3.2.9 on 2021-11-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_auto_20211115_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_masspoints_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.case')),
            ],
        ),
    ]
